### ISSUE TITLE
No such export error

### ISSUE THREAD

**Issue by TheOldHook** [milotiro95/XNLRankBar#1]
Hello, 

Nice script you have here. 
I got some issue when im trying to implement the check xp on a script i have.

Error img:
https://imgur.com/a/ZPqbHsk

The resource code:

`
RegisterNetEvent('qbdriftmode:DriftMode', function()
	ped = PlayerPedId()
    local ped = PlayerPedId()
	local xp = exports.XNLRankBar:Exp_XNL_GetCurrentPlayerXP()
	local vehicle = GetVehiclePedIsUsing(ped)

	if xp <= 6100 then
		QBCore.Functions.Notify("❌ You need to be level 5..", "error")
	end
	if GetVehicleHandlingFloat(vehicle, "CHandlingData", "fInitialDragCoeff") < 90 then
		SetVehicleEnginePowerMultiplier(vehicle, 0.0)
	else
		if GetVehicleHandlingFloat(vehicle, "CHandlingData", "fDriveBiasFront") == 0.0 then
			SetVehicleEnginePowerMultiplier(vehicle, 190.0)
		else
			SetVehicleEnginePowerMultiplier(vehicle, 100.0)
		end
	end
	if (GetPedInVehicleSeat(vehicle, -1) == ped) then
		if GetVehicleHandlingFloat(vehicle, "CHandlingData", "fDriveBiasFront") ~= 1 and IsVehicleOnAllWheels(vehicle) and IsVehicleClassWhitelisted(GetVehicleClass(vehicle)) then
			local modifier = 1
			if GetVehicleHandlingFloat(vehicle, "CHandlingData", "fInitialDragCoeff") > 90 then
				driftMode = true
			else
				driftMode = false
			end
			if driftMode then
				modifier = -1
			end
			for index, value in ipairs(handleMods) do
				SetVehicleHandlingFloat(vehicle, "CHandlingData", value[1], GetVehicleHandlingFloat(vehicle, "CHandlingData", value[1]) + value[2] * modifier)
			end
			if driftMode then
				QBCore.Functions.Notify("Drift mode | Off")
			else
				QBCore.Functions.Notify("Drift mode | ON!")
			end
		end
		if GetVehicleHandlingFloat(vehicle, "CHandlingData", "fInitialDragCoeff") < 90 then
			SetVehicleEnginePowerMultiplier(vehicle, 0.0)
		else
			if GetVehicleHandlingFloat(vehicle, "CHandlingData", "fDriveBiasFront") == 0.0 then
				SetVehicleEnginePowerMultiplier(vehicle, 190.0)
			else
				SetVehicleEnginePowerMultiplier(vehicle, 100.0)
			end
		end
	end
end)`

**Comment by milotiro95** [comment]
Sorry the exports work and I don't offers supports for. You just have did shit code sorry I need to be honest with you. Learn how to code first. 

All you need is to learn how to use this  

```
local xp = exports.XNLRankBar:Exp_XNL_GetCurrentPlayerXP()
    if xp >= 6100 then

** YOUR EVENT **

else
        QBCore.Functions.Notify("❌ You need to be level 5..", "error")
    end
```
Per exemple 
```

RegisterNetEvent('qbdriftmode:DriftMode', function()
ped = PlayerPedId()
local ped = PlayerPedId()
local xp = exports.XNLRankBar:Exp_XNL_GetCurrentPlayerXP()
local vehicle = GetVehiclePedIsUsing(ped)

if xp >= 6100 then
if GetVehicleHandlingFloat(vehicle, "CHandlingData", "fInitialDragCoeff") < 90 then
	SetVehicleEnginePowerMultiplier(vehicle, 0.0)
else
	if GetVehicleHandlingFloat(vehicle, "CHandlingData", "fDriveBiasFront") == 0.0 then
		SetVehicleEnginePowerMultiplier(vehicle, 190.0)
	else
		SetVehicleEnginePowerMultiplier(vehicle, 100.0)
	end
end
if (GetPedInVehicleSeat(vehicle, -1) == ped) then
	if GetVehicleHandlingFloat(vehicle, "CHandlingData", "fDriveBiasFront") ~= 1 and IsVehicleOnAllWheels(vehicle) and IsVehicleClassWhitelisted(GetVehicleClass(vehicle)) then
		local modifier = 1
		if GetVehicleHandlingFloat(vehicle, "CHandlingData", "fInitialDragCoeff") > 90 then
			driftMode = true
		else
			driftMode = false
		end
		if driftMode then
			modifier = -1
		end
		for index, value in ipairs(handleMods) do
			SetVehicleHandlingFloat(vehicle, "CHandlingData", value[1], GetVehicleHandlingFloat(vehicle, "CHandlingData", value[1]) + value[2] * modifier)
		end
		if driftMode then
			QBCore.Functions.Notify("Drift mode | Off")
		else
			QBCore.Functions.Notify("Drift mode | ON!")
		end
	end
	if GetVehicleHandlingFloat(vehicle, "CHandlingData", "fInitialDragCoeff") < 90 then
		SetVehicleEnginePowerMultiplier(vehicle, 0.0)
	else
		if GetVehicleHandlingFloat(vehicle, "CHandlingData", "fDriveBiasFront") == 0.0 then
			SetVehicleEnginePowerMultiplier(vehicle, 190.0)
		else
			SetVehicleEnginePowerMultiplier(vehicle, 100.0)
		end
	end
end
	else
	QBCore.Functions.Notify("❌ You need to be level 5..", "error")
	end
end)
```

**Comment by TheOldHook** [comment]
Thanks for the honesty and your quick reply. 
But, I did write it like in your example at first but same error arrived so i tried to write it differently.
Now that i used your example again i still get export error. 

`^1SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export Exp_XNL_GetCurrentPlayerXP in resource XNLRankBar^7`

**Comment by TheOldHook** [comment]
Thanks for your reply.
Everything works fine now.
